version: '3.1'
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 1378026744@qq.com
      PGADMIN_DEFAULT_PASSWORD: Gxk@1024
    links:
      - "db:pgsql-server"
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: gxkai
      POSTGRES_PASSWORD: Gxk@1024
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
